# Generated by Django 6.0.2 on 2026-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('Published_Date', models.DateTimeField()),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('Category', models.CharField(choices=[('Fiction', 'Fiction'), ('Sci-Fi', 'Sci-Fi'), ('History', 'History')], max_length=20)),
                ('Is_available', models.BooleanField()),
            ],
        ),
    ]
